pip install gdown
pip install pandas
pip install scipy 
pip install scikit-learn
pip install seaborn
pip install matplotlib
pip install tqdm
pip install numpy
pip install pillow
pip install torch
pip install torchvision
pip install torchsummary
pip install tensorboard
pip install torchinfo